### ISSUE TITLE
Update ~ 2016-05-31 ~ Sunny days are here

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#29]
![image](https://cloud.githubusercontent.com/assets/547626/15700117/dbb0685c-2786-11e6-80ed-12df0a37adf9.png)

@ladybug-analysis-tools/owners @ayezioro 

The Shadow Range scripts seem to be working. The Core and Gallery scripts are functional. The Opener (editor) is a work in progress.

It took a lot longer than I thought it would. And I should pay with it a few more days playing around and tweaking before thinking about announcing things.

And I will have a good number of questions about to how to begin to make the whole process usable and useful.

Do note that each sun is represented by a 3D box or frustum - helps with debugging. Do you have any good ideas what should be there instead? 

Feel free to play around. Things may free or be slow. Don't be afraid to reload and start over.

Also you can start to look here to see all the scripts:
### [Ladybug Web Project Explorer](https://ladybug-analysis-tools.github.io/ladybug-web/)

---
### 2016-05-31
- Final cleanup before write up
- Add dates to all models

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour! Sorry for not being responsive for the last couple of days.

The shadow range is beautiful. I love the level of control.

Is it possible to add a time-step and an end time instead of number of positions? This will give the user the chance to pick sun positions for finer resolutions than an hour. For instance timestep of 2 returns sun positions for every half an hour.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> Is it possible to add a time-step and an end time instead of number of positions? 

See #32
