### ISSUE TITLE
Status Update ~ 2016-03-21 ~ 'Are we there yet?' Release

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#9]
![image](https://cloud.githubusercontent.com/assets/547626/13933170/1110de56-ef69-11e5-8a15-ceaa96c8258e.png)

Most of the major requirements seem to be met and mostly working as desired. Of course still has bugs and bits to be finished.

New feature added today: yellow sun path band - but still not positioning properly.

The fun thing is that as and when things start settling down we can begin to think about adding disruptive new features - such as adding 3D building data acquired from Google Street View or 3D terrain data.
### Latest update: 2016-03-21 / R9
- Analemmas are no longer upside down
- Calculates analemma for every day of month - not just first 28 as in previous release
- Add transparent yellow band to indicate full Sun path
### Issues
- Sun path band incorrectly positions itself
  - Tries to be its own algorithm - good for checking errors
  - Fall back could be to create sun path band from analemma vertices
- Latitude and longitude sliders not working properly
- Maps not always not updating properly when using lat/lon sliders
- Permalink support (currently broken )

**Comment by mostaphaRoudsari** [comment]
@theo-armour this looks great! Well, actually more than that. It makes me smile! :) I can't wait to use this for teaching. It's very handy. I think it will have more users than any other ladybug and honeybee developments since you have to install nothing but a browser! :tada: 

I think we can ask for the first round of feedback as soon as you feel it's the right time to do it. Maybe once we have the sliders fixed is the good time to know more people about this?

My personal wishes for the first release are:
1. Add arcs for 21 of each month. This will remove the need to have the surface.
   ![image](https://cloud.githubusercontent.com/assets/2915573/13934682/c15fbf82-ef89-11e5-945f-3d9ad936aaef.png)
2. Add a north sign and the ability to change the north based on an angle. Also sun-path circles.
   ![image](https://cloud.githubusercontent.com/assets/2915573/13934706/d8091102-ef89-11e5-82bf-1500489d0ea0.png)
3. Being able to import json files. I'm pretty sure that most of users want to try it with their own buildings.
4. Having the ability to add sun positions for a time-range (21 Dec, 9 am - 5 pm). IMO the main use of the initial release of sun-path will be running shadow range studies.
   ![shadow range analysis](http://api.ning.com/files/ofVqoMLbPfuUF4fewBUG18iAYralYHCBWBhZhGjhzNcCBFgPknlb4Gx5F94c3CKr01souhJGLOSbIuwta*wVE-iAoGXuwCU4/shadowRangeStudy_02.png)
5. Add an option to re-scale the sunpath
6. Add a button for top view and also save view to file.

Also should we start moving some of the code into libraries or do you want to keep it all in the same HTML file?

I have some suggestions for the interface which I will share once I have a prototype.

Let me know if there is anything specific that I can help you with. I love to spend a day or half a day every week to help you with this.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Loved the speedy response!

All your thoughts highly doable.

> > Also should we start moving some of the code into libraries or do you want to keep it all in the same HTML file?

Interesting question.

My current motivation is to help good engineers but beginner programmers coding their thoughts easily and quickly. Large apps and many libraries encumber that process.

I want to explore ways of building more small programs that work together. I want you to open a script, look at it for three minutes or less and be able to say: 'I get it'. My mentor in this is Mr.doob and his 270 examples that he assiduously keeps adding to and refreshing.

Much more on this as we progress...

More on Analemma 3D tomorrow.

Plus some other questions later today...

Theo

**Comment by mostaphaRoudsari** [comment]
> My current motivation is to help good engineers but beginner programmers coding their thoughts easily and quickly. Large apps and many libraries encumber that process.
> 
> I want to explore ways of building more small programs that work together. I want you to open a script, look at it for three minutes or less and be able to say: 'I get it'. My mentor in this is Mr.doob and his 270 examples that he assiduously keeps adding to and refreshing.

@theo-armour that's exactly how and why I started Ladybug and DesignExplorer. I think this approach is great for creating prototypes and as you said it's much easier to learn from them. On the other hand, once it comes to creating full apps with collaboration of several developers having everything in the same place makes it hard to collaborate. It's a lose some gain some condition. It comes down to what we want 3D sunpath to be. I personally picture it as a web app that will have 100s of users on a daily basis.

**Comment by theo-armour** [comment]
Mostapha's items added to road map
